cp index.html aws/
cp index.html aws/arch/
cp index.html aws/sysops/
cp index.html cd/
cp index.html cd/docker/
cp index.html cd/ec2/
cp index.html cd/kubernetes/
cp index.html ci/
cp index.html ci/git
cp index.html ci/github/
cp index.html ci/jenkins/
cp index.html cm/
cp index.html cm/cloudwatch/
cp index.html cm/nagios/
cp index.html manage/
cp index.html manage/chef/
cp index.html manage/puppet/
cp index.html scripting/
cp index.html scripting/bash/
